name: Build OniMask

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - "native/**"
      - "build.py"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: macos-26
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Build release
        run: ./build.py -vr all

      - name: Stop gradle daemon
        run: ./app/gradlew --stop

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: OniMask-release
          path: out/*.apk
          compression-level: 9
          if-no-files-found: error

      - name: Upload mapping and native debug symbols
        uses: actions/upload-artifact@v7
        with:
          name: OniMask-symbols
          path: app/apk/build/outputs
          compression-level: 9

  test-compile:
    name: Test compile (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025]
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Test build
        run: python build.py -v -c .github/ci.prop all

      - name: Stop gradle daemon
        run: ./app/gradlew --stop
